version: '3.8'
services:
  ruinedfooocus:
    image: ghcr.io/hhenne/ruinedfooocus:latest # Change this if you use a different username or image name
    ports:
      - 7860:7860
    volumes:
      - ./ruinedfooocus-code:/app  # Mount the RuinedFooocus code
      - ./outputs:/app/outputs     # Mount a local directory for outputs
    restart: unless-stopped