services:

  ruinedfooocus:
    image: ghcr.io/hhenne1/ruinedfooocus:latest
    container_name: ruinedfooocus
    restart: unless-stopped
    ports:
      - "7865:7865"
    environment:
      - TZ=Canada/Eastern
    volumes:
      - /your/path:/fooocus/cache
      - /your/path:/fooocus/settings
      - /your/path:/fooocus/wildcards
      - /your/path:/fooocus/models/checkpoints
    deploy:
        resources:
            reservations:
                devices:
                    - driver: nvidia
                      count: 1
                      capabilities: [gpu]
