
services:
  ruinedfooocus:
    image: ghcr.io/hhenne/ruinedfooocus1:latest
    container_name: ruinedfooocus
    restart: unless-stopped
    ports:
      - 7860:7860
    environment:
      - TZ=Europe/Berlin
      - CMDARGS=--listen --always-offload-from-vram
    volumes:
      - ./ruinedfooocus/settings:/app/settings
      - ./ruinedfooocus/settings/wildcards:/app/wildcards
      - ./ruinedfooocus/models:/app/models
    deploy:
        resources:
            reservations:
                devices:
                    - driver: nvidia
                      count: 1
                      capabilities: [gpu]
