name: Build and Push Docker Image

on:
  schedule:
    - cron: "0 0 * * 3,6"
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Check for Submodule changes
        id: check_submodule
        run: |
          git diff --name-only --submodule | grep 'ruinedfooocus-code' || false
          if [ -n "$(git diff --name-only --submodule | grep 'ruinedfooocus-code')" ]; then
            echo "SUBMODULE_CHANGED=true" >> $GITHUB_ENV
          else
            echo "SUBMODULE_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        if: env.SUBMODULE_CHANGED == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: env.SUBMODULE_CHANGED == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: env.SUBMODULE_CHANGED == 'true'
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/ruinedfooocus:latest ./ruinedfooocus-code
          docker push ghcr.io/${{ github.repository_owner }}/ruinedfooocus:latest
